# Generated by Django 4.1.2 on 2022-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="FirstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="LastName",
            new_name="last_name",
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(),
        ),
    ]
