# Generated by Django 4.1.2 on 2022-10-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_account_account_this username is taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="account",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.account",
                verbose_name="Account",
            ),
            preserve_default=False,
        ),
    ]
