# Generated by Django 4.1.2 on 2022-10-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_parent_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=200)),
            ],
        ),
    ]
