# Generated by Django 4.1.2 on 2022-10-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokens",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.parent",
            ),
            preserve_default=False,
        ),
    ]
