# Generated by Django 4.1.2 on 2022-10-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_tokens_parent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tokens",
            new_name="Token",
        ),
    ]
