# Generated by Django 4.1.2 on 2022-10-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_rename_tokens_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="student.parent",
            ),
        ),
    ]
